### ISSUE TITLE
ADLATUS Export for 010 Editor

### ISSUE THREAD

**Issue by Mr-MIBonk** [jilleb/mqb-soundaktor#10]
some guy's ask me for this, possible it is helpfull for your repository. Many thank's for your good work 

[FL_xx__x.odx.FD_2DATA_export.zip](https://github.com/jilleb/mqb-soundaktor/files/8131462/FL_xx__x.odx.FD_2DATA_export.zip)

**Comment by jilleb** [comment]
Merged, thanks! :-)
