### ISSUE TITLE
Soundactor without FPA

### ISSUE THREAD

**Issue by malison88** [jilleb/mqb-soundaktor#12]
Hello Guys,
Unfortunately I don't have an FPA in my Golf MK7 1.4 TSI. Does the soundactor work in "Normal" mode as default (with the unlocked firmware)? Or does it not work without FPA at all? Thank you in advance!

**Comment by jilleb** [comment]
Yes, that's possible. You would need to modify the firmware in such a way that it has a profile with sound linked to the normal and default profiles.

**Comment by xiaxiaxiamagic** [comment]
so it won’t work without FPA?

**Comment by jilleb** [comment]
Yes it will

**Comment by malison88** [comment]
Hello Jille,
Can you please so kind and modify a gen 2.0 firmware which can works without the FPA? I think that the sport/race setting would be great as default (because we can decrease the volume of the soundactor). I can retrofit the modules and upload the firmware with the ODIS, but I don’t have the proper programmer skills to modify a firmware. Thanks a lot in advance

**Comment by jilleb** [comment]
Allright, which one would you like me to modify?

**Comment by xiaxiaxiamagic** [comment]
> Allright, which one would you like me to modify?

RS4！

**Comment by jilleb** [comment]
[FL_8W0907159D__0006_UNLOCKED_default_Sport.zip](https://github.com/jilleb/mqb-soundaktor/files/8471056/FL_8W0907159D__0006_UNLOCKED_default_Sport.zip)

Let's see if that works :-)

**Comment by malison88** [comment]
Hello Guys,

**gehot**: Can you please send us a feedback if it's works? I can't test it yet, I'm still waiting for the module holder.
**jilleb**: Thank you very much for your job! Can you please modify a Golf GTI or GTI Clubsport firmware as well ? I don't know which has more feeling in the car. I heard the soundactor only in my friend's car which is a 7.5 GTI Performance, it sounds not bad :)

**Comment by jilleb** [comment]
@malison88, as soon as @gehot reports back that this is indeed working, I will convert all the firmwares for non-FPA use.

**Comment by xiaxiaxiamagic** [comment]
After my test it works well. You can hear the V6 engine sound in S gear.

**Comment by malison88** [comment]
My car has a manual 6 gear transmission, it should work with it as well, right?

**Comment by jilleb** [comment]
> My car has a manual 6 gear transmission, it should work with it as well, right?

Yes, it might need some tweaking because there's also a gearbox type flag on the firmware but it should work 😎

**Comment by monstermolt** [comment]
Hi,
first of all thanks for the work.
Can you change the RS4 so that it only produces sound in GTE mode?
With my Passat GTE is
E mode FPA 2
Hybrid FPA 2
Battery Hold FPA 2
GTE FPA 7

**Comment by Mr-MIBonk** [comment]
> Yes, it might need some tweaking because there's also a gearbox type flag on the firmware but it should work 😎

Happy Easter and thanks for your great work! 
Can you explain what happens when the gearbox type is changed, please?

**Comment by Mich795** [comment]
Hi, I don't understand a point.. can the "open firmware" be loaded as it is on any mqb car or is it necessary to edit with 010 Editor? I opened the file and I noticed some submenus like "struct Car" which contain information about VIN and Engine code (sorry but I'm not very experienced, but I would like to learn).. thank you

**Comment by jilleb** [comment]
> Hi, I don't understand a point.. can the "open firmware" be loaded as it is on any mqb car or is it necessary to edit with 010 Editor? I opened the file and I noticed some submenus like "struct Car" which contain information about VIN and Engine code (sorry but I'm not very experienced, but I would like to learn).. thank you

Yes, it can be loaded and doesn't need to be modified. If you want to modify it, then the best place would be to do a quick tour through the functions of 010 editor (they have a pretty nice wiki page) before making any attempt :-)


> Hi, first of all thanks for the work. Can you change the RS4 so that it only produces sound in GTE mode? With my Passat GTE is E mode FPA 2 Hybrid FPA 2 Battery Hold FPA 2 GTE FPA 7
Yes that's possible. But can you please start a seperate post for that, to prevent cluttering this topic?


> > Yes, it might need some tweaking because there's also a gearbox type flag on the firmware but it should work 😎
> 
> Happy Easter and thanks for your great work! Can you explain what happens when the gearbox type is changed, please?

Thanks! The gearbox flag, I've seen 2 things happening so far:
- nothing changes
- it determines whether or not the sound is changing to sport when shifting to S from D or E mode.

**Comment by Cuzoe** [comment]
> > My car has a manual 6 gear transmission, it should work with it as well, right?
> 
> Yes, it might need some tweaking because there's also a gearbox type flag on the firmware but it should work 😎

Do you think this could be the problem I am having?  I have FL_8S0907159___0004_UNLOCKED_2.odx installed but I hear no sounds.  I think the Audi TT-S/RS only come with DSG.  My car is 6MT.  If I switch modes between Eco, Comfort, Normal and Sport (or change modes using the dropdown in Custom) while looking at the measuring values of the soundaktor module in VCDS everything looks correct.

Driving Profile selection-System Status... available
Driving Profile selection Act. val... 2 (changes when I change modes)
Driving Profile selection-Target Value... 2 (changes when I change modes)
Driving Profile selection-Compatibility Yes

No errors in the module, VCDS output test works, very loud.

**Comment by jilleb** [comment]
That's very plausible.

I'm currently on vacation, let's do some tests as soon as I'm back

**Comment by Cuzoe** [comment]
Sounds good, enjoy the time away!

**Comment by malison88** [comment]
The modified FL_8W0907159D__0006_UNLOCKED_default_Sport.zip software is working fine in my 2014 Golf 1.4 TSI car, 6 gear manual transmission, without FPA :))
So jilleb, can you please so kind and modify the other firmwares in same method as you mentioned before? :D
Thanks in advance, have a nice holiday!

**Comment by Cuzoe** [comment]
Figured I'd come back in here with an update.  So in a previous post I was running FL_8S0907159___0004_UNLOCKED_2 and got no sound in any modes.

Earlier @jilleb posted FL_8W0907159D__0006_UNLOCKED_default_Sport which was modified for default Sport mode.  I figured to give that a try, even though my car has Driving Modes.  Well... with this firmware everything works in my car, 6MT. 
Eco/Comfort (same sound), Normal, and Sport.

It took me a while to notice because I always drive in Comfort mode, or in Individual with all settings set to Comfort except Steering.

@jilleb Besides changing the default sound (and tables of course), is the only difference between these that the RS4 would be a manual transmission?  If so maybe that's the key.  From my quick search the RS4's are manual and TT-R was only DSG, (firmware I was running).

**Comment by malison88** [comment]
Hello @jilleb , Can you please modify the 
FL_5G0907159___0014_UNLOCKED_2.odx and FL_5G0907159___0014_UNLOCKED_3.odx firmwares to work without FPA? Thank you!

**Comment by HansenRS** [comment]
> [FL_8W0907159D__0006_UNLOCKED_default_Sport.zip](https://github.com/jilleb/mqb-soundaktor/files/8471056/FL_8W0907159D__0006_UNLOCKED_default_Sport.zip)
> 
> Let's see if that works :-)

Hello @jilleb i tested these File on my 2018 VW UP GTI. The GTI has no Driving Mode. The Actor doesn´t work anymore, no Problem, i will Test more. 
I get with these File an Error:
![IMG20220601120656](https://user-images.githubusercontent.com/106811607/171852824-832e97c3-b49e-45de-bb90-c7988dcabc97.jpg)
Maybe it doesn´t work because of the Error. The can´t be erase.
i change all Strings 8W0907159D_0006 in to 4H0907159A_0003 with the 010 Editor, but still get the Error.
File:
[FL_4H0907159A__0003_UNLOCKED_default_Sport_1.zip](https://github.com/jilleb/mqb-soundaktor/files/8832321/FL_4H0907159A__0003_UNLOCKED_default_Sport_1.zip)
Any Solution or Tip?
Greets Hansen
p.s. only School English from 40 Years ago ;-)

**Comment by Sensei1978** [comment]
FL_8W0907159D__0006_UNLOCKED.odx

Can you make this file without fpa?

**Comment by malison88** [comment]
> FL_8W0907159D__0006_UNLOCKED.odx
> 
> Can you make this file without fpa?

https://github.com/jilleb/mqb-soundaktor/files/8471056/FL_8W0907159D__0006_UNLOCKED_default_Sport.zip

This firmware is working fine without FPA.

**Comment by malison88** [comment]
> > FL_8W0907159D__0006_UNLOCKED.odx
> > Can you make this file without fpa?
> 
> https://github.com/jilleb/mqb-soundaktor/files/8471056/FL_8W0907159D__0006_UNLOCKED_default_Sport.zip
> 
> This firmware is working fine without FPA.

But this is the only one fw which can works without FPA. It has a "big block" V6 sound, too much for a 1.4 TSI for example. 
I hope that jilleb will come back to the board and he can modify the other firmwares as well.

**Comment by Sensei1978** [comment]
Can i flash this to a Golf 7 GTI?

**Comment by malison88** [comment]
I have a before facelift 1.4 TSI Golf 7 with 6MT gearbox and a soundactor module from a Golf 7 R. This fw is working fine in my car. One guy tested this firmware in his DSG equipped car, it has sound only in "S" gear, if I understood well his feedback.

**Comment by Sensei1978** [comment]
Thank you.
Where can i get the original flashfile FL_5G0907159___0014_UNLOCKED_2.odx for my GTI when i will get back?
Without FPA.

**Comment by malison88** [comment]
If I know well there are not available GTI firmware for "without FPA" cars. @jilleb can modify the mentioned firmware to works without FPA. But he left this project or I don't know. He was very helpful in the past, I hope that he will return soon.

**Comment by jilleb** [comment]
> If I know well there are not available GTI firmware for "without FPA" cars. @jilleb can modify the mentioned firmware to works without FPA. But he left this project or I don't know. He was very helpful in the past, I hope that he will return soon.

Please don't spread misinformation. I didn't leave the project. I just have other things in life that have higher priority, like my daytime job and family. The without-fpa firmwares are in the works. Just be patient, this is not my job 😅

**Comment by Sensei1978** [comment]
Yes i understand you. It were nice if i could have an original soundfile from my Golf GTI in the future, to flash back to original.

**Comment by jilleb** [comment]
I've updated the wiki and uploaded all firmwares with a version that works on non-FPA cars. Enjoy!

**Comment by Sensei1978** [comment]
Thank you very much for your work.

**Comment by FPSUsername** [comment]
I have a 5Q0 gateway (A3 8V Limousine 1.4TFSI (CZEA, QSZ) MY 2015), and I can select between auto, efficiency, comfort, dynamic and individual (where I can only select steering wheel and engine between comfort and auto).
Does that qualify as having FPA or is FPA a facelift generation thing?

As I installed the system today, I checked coding in 5F and saw on byte 11 that bit 6 was selected (start counting from 0), with the following description:
![image](https://user-images.githubusercontent.com/10143926/177014947-6699ba92-4648-4a85-bf22-66dfb03da743.png)

Shouldn't it be 01 Internal Sound System Active? (As I installed the 159A module).

**Comment by Cuzoe** [comment]
FPA is driving profiles and yes you do have them. Those are the different modes you can select.

As far as coding, it looks like you are in 5F Infotainment.  So those options that you pictured are to choose whether your radio is using its internal speaker amp or an external speaker amp like Fender or Dunaudio.

Search for soundaktor retrofit on Google and a few different forum threads should come up.  You need to enable the sound actor in the 19 - Gateway installation list and also in the gateway long coding.  When you go to Gateway Long coding choose "use experimental" and look for something like "FPA sak" (I can't remember exactly what it says but it's something like that).

**Comment by FPSUsername** [comment]
Yes, I've enabled the installation list, but couldn't find the `FPA_Function_SAK`. For me Byte 11 Bit 5 in the gateway is something totally different (although I don't have a screenshot right now to provide the information).

I'll check the "use experimental" tomorrow.

I followed this [guide](https://mqb-blog.com/en/2021/06/14/sak/).

Thanks for confirming that I do have FPA.

**Comment by Cuzoe** [comment]
If you did not select experimental then VCDS probably didn't show you byte 11-bit 5. It might have showed you something else in byte 11.  

Once you select use experimental I think you'll be good to go.  That will show you every bit, 0-7.

**Comment by FPSUsername** [comment]
I have successfully flashed 8S0 (TTRS) unlocked 1, no errors in ODIS. I did the output test and that works, but no engine sound during driving (I pushed it to 6k RPM).
I cycled through all profiles (eco/comfort/dynamic/individual/auto) but still nothing.
Adaptation volume is set to 100%.

I'll try the "no FPA" variants later today and also check if any coding isn't correct (which I doubt)
