### ISSUE TITLE
Diesel engine firmware

### ISSUE THREAD

**Issue by Mich795** [jilleb/mqb-soundaktor#13]
Hi, I retrofitted the control unit and the speaker on A3 8V diesel, loaded the file FL_5G0907159 ___ 0014_UNLOCKED_1.odx (Golf GTD) and everything works perfectly (Thanks!). I have tried other firmwares, in particular FL_8S0907159___0004_UNLOCKED_1.odx (TT any engine) but it sounds very low, almost non-existent. I also tried the TT firmware for petrol engines (FL_8S0907159___0004_UNLOCKED_2.odx and FL_8S0907159___0004_UNLOCKED_3.odx), but there is no sound (as I expected). 
My question is: is it possible to adapt petrol to diesel firmware? 
I  would be curious to understand if it's possible, I assume also the audio is to be adapted according to engine rpm, which are not the same in diesel and petrol and so I would try TT rs to see how it sounds..

Thank you :)

**Comment by Cuzoe** [comment]
My car is a diesel and I'm currently running RS4 firmware, from https://github.com/jilleb/mqb-soundaktor/issues/12#issuecomment-1096342679.  It works great, and gets quite loud.  It does not seem to matter petrol or diesel.  On the diesel maybe we will never hear soundaktor sounds of 7k RPM, but it still works.

Possibly you are having an issue I had with FL_8S0907159___0004_UNLOCKED_2, which seemed to be that it was for a car with DSG, and my car is manual.  I had no sound with that firmware (or maybe it was very quite, but I could not notice it).  RS4 is a manual car.

**Comment by Mich795** [comment]
My car is manual too, but I have the selection of driving profiles (and I understand that the firmware you are talking about has been adapted for those who do not have this setting) and I would like to be able to keep the "comfort" option with a quiet sound for long distances.. As you say the problem could be due to the fact that my car does not have a DSG gearbox, maybe it could be possible to fix this thing to make the firmware compatible with the manual gearbox.. I'm not so expert unfortunately

**Comment by Cuzoe** [comment]
I also have driving profiles.  I only tried the modified file because I found the TT files produced little/no sound (as you also noticed).

I expected the modified file to produce Sport mode sound at all times, but was happy to find that is not the case.  I suspect the modification made was so that it would produce the Sport mode sound anytime it does NOT receive a driving profile mode command.  But since my car, like yours, does have driving profiles those commands override the "default=Sport" modification.

The modified file is very subtle in Comfort & Eco (which both use the same sound table), audible in Normal but not too much in your face, and quite loud in Sport (sounds really good, but I won't drive around like that most days).

**Comment by Mich795** [comment]
Interesting, we have to understand if this change is possible for other firmware too.. Anyway, I'll try RS4 firmware you say, I'm curious :)

**Comment by Cuzoe** [comment]
Did you get a chance to try it? How is it working for you, if at all?

**Comment by Mich795** [comment]
Hi, yes I tried and it works as you say :), but I don't notice much sound difference in profile changes and when you change gear down it doesn't seem to make a sound (instead fw for golf seems fine from this point of view).. Would be to try with with that TT's firmware or other adapted firmware

**Comment by Cuzoe** [comment]
Interesting, sound is very different to me.  If you have VCDS you can check Advanced Measuring Values for the A9-Soundaktor and verify it is also changing modes when you select them.

I will give FL_5G0907159 ___ 0014_UNLOCKED_1.odx (GTD) file a try as you had originally to see how it sounds.  I never tried it, went straight to Audi cars, haha.  GTD file is more appropriate for my car though, similar CR 2.0 TDi.

**Comment by Mich795** [comment]
Let me know.. I will try to check with vcds, however fw for gtd seems to me more adequate for everyday use... but every now and then I will flash rs4 fw for fun

**Comment by vexovex** [comment]
> Hi, I retrofitted the control unit and the speaker on A3 8V diesel, loaded the file FL_5G0907159 ___ 0014_UNLOCKED_1.odx (Golf GTD) and everything works perfectly (Thanks!). I have tried other firmwares, in particular FL_8S0907159___0004_UNLOCKED_1.odx (TT any engine) but it sounds very low, almost non-existent. I also tried the TT firmware for petrol engines (FL_8S0907159___0004_UNLOCKED_2.odx and FL_8S0907159___0004_UNLOCKED_3.odx), but there is no sound (as I expected). My question is: is it possible to adapt petrol to diesel firmware? I would be curious to understand if it's possible, I assume also the audio is to be adapted according to engine rpm, which are not the same in diesel and petrol and so I would try TT rs to see how it sounds..
> 
> Thank you :)

I changed Octavia file from Petrol to Diesel and it is way better and louder.
Also I think I have 8S0 version for Diesel.
Let me know if you want to try it; I'll send you.
BR,
Vex

**Comment by Mich795** [comment]
That would be great, I'd be curious to try it :)

**Comment by vexovex** [comment]
Here you go!
Test it!
If all ok, Jille can upload it on FWs list if he wants. :-)

[Diesel - 5E0&8S0.zip](https://github.com/jilleb/mqb-soundaktor/files/9176603/Diesel.-.5E0.8S0.zip)

BR,
Vex

**Comment by Mich795** [comment]
Thank you! I'll try it later :)

**Comment by Mich795** [comment]
> Here you go!
> 
> Test it!
> 
> If all ok, Jille can upload it on FWs list if he wants. :-)
> 
> 
> 
> [Diesel - 5E0&8S0.zip](https://github.com/jilleb/mqb-soundaktor/files/9176603/Diesel.-.5E0.8S0.zip)
> 
> 
> 
> BR,
> 
> Vex

Hi, I tested them... 8S0 seems to work (Thanks!).. about 5E0 I don't notice any differences
