### ISSUE TITLE
Error ODS05110/VW 80128-3

### ISSUE THREAD

**Issue by bukato** [jilleb/mqb-soundaktor#14]
Hi.When the block is being flashed, the error "Failed to load the firmware container. The format does not correspond to the data of the specification "VW 80128-3" for the ODX firmware container".
At the same time, other blocks are successfully stitched.
What should I do?
Thanks!

**Comment by xmancz** [comment]
I have same problem, same error. Did you solve it somehow? ODIS-E 12.2

**Comment by jilleb** [comment]
What module are you flashing onto? It could happen with some Audi-devices that it generates this.  It can be fixed, by using the modified data2 file with the data1 and data0 from an OEM Audi firmware.

**Comment by Krosta8** [comment]
Maybe it is totally different topic, but I was getting very similar error for ODX firmware container. Solution was very simple. The file was located on a very long path name. When I placed it on desktop, it was without issue. 
Maybe it is the same problem. I was getting this error after I started the flash.

**Comment by xmancz** [comment]
I flash modul 5E0 907 159 (Skoda Octavia) today I will try another version of ODIS-E, someone recommends an older version.

**Comment by bukato** [comment]
I am flashing a block with SW 3G8907159 on my VW Passat b8.  Wherever I place the firmware file, the error repeats.  Now I want to find another non-hacked firmware.

**Comment by xmancz** [comment]
today I try flash with ODIS-E 9.2.2 with file **FL_5F0907159A__0002_UNLOCKED.odx** and get same error "VW 80128-3" for the ODX firmware container"

**Comment by xmancz** [comment]
I solved this problem for me, I must download firmware from here : https://github.com/jilleb/mqb-soundaktor/wiki/Download-unlocked-firmwares

All the time I was download firmware from here : https://github.com/jilleb/mqb-soundaktor/tree/main/Firmwares and this is it a problem.

Now I successful flash with ODIS-E 12.2
