### ISSUE TITLE
Firmware swap

### ISSUE THREAD

**Issue by xmancz** [jilleb/mqb-soundaktor#17]
Hi, on drive2.ru you write that version of the internal sound control module (xXx 907 159) is vitually identical and the firmware is identical.

It is possible to upload firmware designed for example unit **8W0907159** (Audi) upload to unit **5E0907159** (Skoda)

Thank you

**Comment by Cuzoe** [comment]
Yes, 159 to 159 is okay.  You cannot flash 159 to 160, or 160 to 159.
