### ISSUE TITLE
RS4 sound does not change with different profiles

### ISSUE THREAD

**Issue by FPSUsername** [jilleb/mqb-soundaktor#21]
I have flashed `FL_8W0907159D__0006_UNLOCKED.odx` successfully, however, when I change between driving profiles, I do not hear any difference (for example, in eco/comfort mode, it's still as loud as in dynamic).

I have a manual Audi A3 2015 (pre facelift) with a 5Q0907530M gateway and its software is 5Q0907530T.

Perhaps FPA profiles only work on 3Q0 gateways from facelift models?

**Comment by FPSUsername** [comment]
So it seems like the gateway (SW: 5Q0 907 530 T    HW: 5Q0 907 530 M) does not send any values to the A9 module, meaning that the car is basically a "NOFPA" version .. with FPA.

![image](https://user-images.githubusercontent.com/10143926/179404717-5f86bdd5-2487-48ee-bd39-37741eadcc98.png)
![image](https://user-images.githubusercontent.com/10143926/179404725-f906869b-70bc-48fe-8b8c-7e762c63d97e.png)


`FPA_Funktion_SAK` is active in the gateway.

So the only (software) option is to modify the 5Q0 dataset to have SAK configured, unfortunately I don't have the dataset (and I don't think we can pull it from the unit).

The other option ofc. is to upgrade to a 3Q0 gateway.

**Comment by jjff2** [comment]
you have to give value to each driving profile for engine sound in 8fb.

**Comment by FPSUsername** [comment]
The issue is that I connected the SAK to the wrong CAN bus (and, surprisingly, no errors). GW dataset is good.
I thought that the GW extension harness extended the powertrain CAN bus.

**Comment by jjff2** [comment]
> The issue is that I connected the SAK to the wrong CAN bus (and, surprisingly, no errors). GW dataset is good.
> I thought that the GW extension harness extended the powertrain CAN bus.

Wow you connect to the wrong bus🙃and GW still recognize it🧐

**Comment by FPSUsername** [comment]
> > The issue is that I connected the SAK to the wrong CAN bus (and, surprisingly, no errors). GW dataset is good.
> > I thought that the GW extension harness extended the powertrain CAN bus.
> 
> Wow you connect to the wrong bus🙃and GW still recognize it🧐

Yes, I think I put it in the green or blue extended canbus (don't remember the exact name). I did change it to the one to check if errors appeared and they did. So apparently you can plug it in the incorrect bus and still get all information except driving profile.
