### ISSUE TITLE
Completely disable sound on eco / comfort?

### ISSUE THREAD

**Issue by SURViR** [jilleb/mqb-soundaktor#34]
Hi! I warted to try to make this by myself but I have no idea how to load hex to 010 editor I don't know why. And I wonder if there is possibility to make sound (Gen2 RS4 sound) go completely off on some drive profiles to make drive more comfortable.

Thanks! :)

**Comment by jilleb** [comment]
Yes, that's possible. If you use 010 Editor, and paste the hex data in there, run the template, you will see the following:
![image](https://github.com/jilleb/mqb-soundaktor/assets/8352494/0727c361-057a-42d2-9468-c743e809d910)


On the right, in the Variables section, you will find Car[0], with Charisma_09_Eco_driving_profile and a value next to it. Thi svalue is the profile it uses in Eco mode. In the case of this screenshot, Profile 7 is selected in Eco and Offroad, and in this firmware Profile 7 seems to be quiet:
![image](https://github.com/jilleb/mqb-soundaktor/assets/8352494/b545ab23-6f97-4870-89a5-cf32241a51f1)

**Comment by SURViR** [comment]
Thank you - I managed to customise it in the way that I wanted - if I put car on eco / comfort sounds disables!
