### ISSUE TITLE
Soundaktor on A3 e-tron (hybrid car)

### ISSUE THREAD

**Issue by chefranov** [jilleb/mqb-soundaktor#41]
Hi! I retrofitted Soundaktor on my Audi A3 2017 Sportback e-tron, I `added A9 module in Gateway` and coded `Byte 19 Bit 5`. I flashed with unlocked SW (tried with/without FPA). But I have one error in A9 and it doesn't work:
> CAN, no message
> U1121 Keine Funktion durch CAN FehlerMotorsteuergerätebotschaft fehlt-> keine Klangerzeugung

![image](https://github.com/jilleb/mqb-soundaktor/assets/2775475/22c1bdc8-b629-4e52-8869-ae0f808e0301)

Maybe for hybrid car need more coding or another FW? I have Drive Select. VW Golf GTE similar to my car and there is working fine from factory.

**Additional info about my modules:**
```
01 Engine
R4 1.4l TFS CXUA
SW: 3695
AO: H22
Part No. 04E906023AN
Part AO: 04E907309F
Coding: 021D0012636405083000

19 Gateway
Version SW:  6286
Version АО:  615
Part No VW/Audi:  3Q0907530D
Part No АО:  3Q0907530D
Coding: 0201001726E200005B00123C581200000001010100010000000300000000

17 Instrument Cluster
SW: 0069
Version  АО: H14
Part No: 8V0920894A
Part AO: 8V0920894
Coding: 046D0CD16E9C00082B83EA171B00000000000000
```

**Comment by jilleb** [comment]
Which firmware did you flash exactly?

Also make sure your FPA dataset in your gateway has soundaktor support, otherwise it will not work.

**Comment by chefranov** [comment]
> Which firmware did you flash exactly?
I tried these:
- FL_3G0907159___0006_UNLOCKED_1.odx
- FL_8W0907159D__0006_UNLOCKED_NOFPA.odx
- FL_8S0907159___0004_UNLOCKED_1.odx

> Also make sure your FPA dataset in your gateway has soundaktor support, otherwise it will not work.

How can I check it?

Maybe my engine missed in dataset?

**Comment by jilleb** [comment]
I will search for A3 etron/hybrid fpa datasets. It's not possible to see what dataset is currently in your car, unless you have access to online Vw/Audi ODIS. 

The fpa dataset has a list of supported modules and settings for each module in each mode. If soundaktor is not there, there will be no message to the soundaktor.

**Comment by chefranov** [comment]
> The fpa dataset has a list of supported modules and settings for each module in each mode. If soundaktor is not there, there will be no message to the soundaktor.

Is possible to use without FPA?

**Comment by jilleb** [comment]
Only with the nofpa firmwares. You can try a few of them.

**Comment by chefranov** [comment]
> Only with the nofpa firmwares. You can try a few of them.

I tried but issue is the same

**Comment by chefranov** [comment]
Could you make dataset for GTE without FPA? My car is similar to GTE

**Comment by jilleb** [comment]
I'll make a few test firmwares for you tomorrow, with Audi firmwares as a base, that should work. There's a slight difference between Audi and VW firmwares, the other parts of the firmware can be different which can be the reason for this

**Comment by chefranov** [comment]
> I'll make a few test firmwares for you tomorrow, with Audi firmwares as a base, that should work. There's a slight difference between Audi and VW firmwares, the other parts of the firmware can be different which can be the reason for this

Thank you! Will wait

**Comment by chefranov** [comment]
> I'll make a few test firmwares for you tomorrow

@jilleb any news?

**Comment by chefranov** [comment]
@jilleb any updates?

**Comment by jilleb** [comment]
Had some surprise deadline at work, so you have to be a bit more patient 😅

**Comment by chefranov** [comment]
@jilleb still deadline at work? 😅

**Comment by jilleb** [comment]
No, but work builds up over time ;-)

Try this:
https://www.dropbox.com/scl/fi/r9jaqzang5xwvycsvk44x/FL_3G0907159___0006.MODIFIED_DEFAULT_GTE.odx?rlkey=82va7vnrkey9m9n9wel88xjoo&dl=0
Regular GTE firmware, has default sound ON, so it should work even when gateway isn't sending any signal (because the soundaktor is not in the FPA dataset)

or this:

https://www.dropbox.com/scl/fi/8awxhat6ztdlac897h3zz/FL_3G0907159___0006.MODIFIED_WITH_AUDI_DRIVER.odx?rlkey=egrquvxb7g5q17bw01r06q60k&dl=0
The same firmware settings, but added to an Audi firmware.



Or this:

https://www.dropbox.com/scl/fi/kxmrwxehlh6sn4oll9spj/FL_3G0907159___0006.MODIFIED_DEFAULT_GTE.MODIFIED.odx?rlkey=h1mye6y2zphgszt201i9b2aow&dl=0
The same regular firmware as the first, but in "negative mode" for sound. This sometimes works between Audi/VW. Worth a try.

**Comment by chefranov** [comment]
Thank you! Will check

**Comment by chefranov** [comment]
@jilleb hi! Today I tried your fw.

**These can't be installed. ODIS can't flash it:**
FL_3G0907159___0006.MODIFIED_DEFAULT_GTE.MODIFIED.odx
FL_3G0907159___0006.MODIFIED_DEFAULT_GTE.odx

**This was installed:**
FL_3G0907159___0006.MODIFIED_WITH_AUDI_DRIVER.odx

**But now I have two errors instead of one as before:**
```
P1385 - Keine Funktion durch internen Fehler des Controllers-> keine Klangerzeugung
U1121 - Keine Funktion durch CAN FehlerMotorsteuergerätebotschaft fehlt-> keine Klangerzeugung
```

**Comment by chefranov** [comment]
@jilleb hi! Any news? I found [here](https://github.com/chobott/MQB-19-Gateway-EV-GTE/tree/main/Datasets) datasets of gateway but for e-golf maybe it can help you

**Comment by chefranov** [comment]
Hi @jilleb! Did you have a chance to find solution for me?

**Comment by chefranov** [comment]
@jilleb heeeelp me please 🥺

**Comment by chefranov** [comment]
Fixed. I connected to incorrect CAN Extended (CAN5). Correct one is CAN Drivetrain (CAN1). 
CAN for Engine and A9 should be are the same:

![image](https://github.com/jilleb/mqb-soundaktor/assets/2775475/e65d3b0d-c1d7-429b-8dcd-c0afe76708f2)

![image](https://github.com/jilleb/mqb-soundaktor/assets/2775475/d29b193b-75ee-4afe-8247-dc3bbec123cd)

**Comment by capisci2000** [comment]
Hi everyone, I wanted to ask if it is possible to load the RS5 firmware onto a Passat GTE without driving profiles, but only with GTE mode. It is possible to modify the file in order to have the RS5 sound only in GTE mode. I think A3 E-tron is similar
Thank you
