### ISSUE TITLE
Unexpected end of file

### ISSUE THREAD

**Issue by jilleb** [jilleb/mqb-soundaktor#9]
Hi,

Sorry maybe a stupid question but I'm not able to parse this file directly with the template. Now I'm not sure should I just take the binary part and paste it as a new hex file or what?
It also fails at some point in parsing with unexpected end of file. I would like to have this file modified so that it works with 1.2TSI engine Hatchback Leon :
[FL_5F0907159B__0004.zip](https://github.com/jilleb/mqb-soundaktor/files/7915334/FL_5F0907159B__0004.zip)
)

_Originally posted by @downtime358 in https://github.com/jilleb/mqb-soundaktor/issues/5#issuecomment-1018682979_

**Comment by jilleb** [comment]
@downtime358, you should indeed take the binary part, which is between the <data> tags. 
There's one part which is about 56kB, that's the one you need.

**Comment by downtime358** [comment]
Ok thanks. That was my impression as well :) Ok I will try with that when I get my bench ready in few minutes. Thanks.
